language: go
os: linux
dist: bionic

jobs:
  include:
    - go: 1.13.x
    - go: 1.14.x
    - go: 1.15.x
    - go: master
  allow_failures:
    - go: master

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet $(go list ./... | grep -v /vendor/)
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
