language: go
os: linux
dist: bionic

jobs:
  include:
    - go: 1.13.x
    - go: 1.14.x
    - go: 1.15.x
    - go: master
  allow_failures:
    - go: master

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
