name: Tests
on:
  push: { }
  workflow_dispatch: { }
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v5
  test:
    strategy:
      matrix:
        go-version:
          - 1.x
          - 1.15.x
          - 1.22.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: make test
      - uses: codecov/codecov-action@v4
        if: matrix.go-version == '1.22.x'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
